cux:
  tag: '&8[&6&lOwner&8] &9Cux'
  id: '@U038KRF3V'
jo_dan:
  tag: '&8[&6&lOwner&8] &aJo_Dan'
  id: '@U04BQ43SY'
blitzkim2:
  tag: '&&8[4Admin&8] &d&k2&bBlitz&cSolo&d&k2'
  id: '@U040T35AF'
pinkyboy:
  tag: '&dPinkyBoy'
  id: '@U0KJSR7S4'
joheinous:
  tag: '&fJoheinous'
  id: '@U040YTX7A'
everyone:
  id: '!everyone'