name: SlackChatBungee
main: io.thejunct.SlackChatBungee.Main
description: Slack hook for Minecraft. By PantherMan594. (c) The Junction Network.
version: #VERSION#
author: PantherMan594
depends:
- BungeeEssentials